---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${NAMESPACE}
  name: chaos-client
  labels:
    app: chaos-client
spec:
  replicas: ${CLIENT_REPLICAS}
  selector:
    matchLabels:
      app: chaos-client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chaos-client
    spec:
      containers:
        - name: client
          image: ${IMAGE}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          command:
            - /frontend
---
apiVersion: v1
kind: Service
metadata:
  namespace: ${NAMESPACE}
  name: chaos-client
  labels:
    app: chaos-client
  annotations:
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: chaos-client
