---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: chaos
  name: chaos-server
  labels:
    app: chaos-server
spec:
  selector:
    matchLabels:
      app: chaos-server
  template:
    metadata:
      labels:
        app: chaos-server
    spec:
      terminationGracePeriodSeconds: 240
      containers:
        - name: server
          image: gotwarlost/chaos-adapter:latest
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          command:
            - /backend
            - "--exit-delay=2m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: chaos
  name: chaos-server
  labels:
    app: chaos-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: chaos-server
---
# we define the rando-server to give us something to delete so as to force a quick pilot update
# (or whatever the heck it is that tickles changes to the envoy config. This is only required on a
# stable cluster where nothing is changing. In our clusters where services are being updated all the time
# no extra tickling is needed)
apiVersion: v1
kind: Service
metadata:
  namespace: chaos
  name: rando-server
  labels:
    app: rando-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: rando-server
