@startuml

node "Client Pod" {
    [Client] as cc
    [Client Envoy Proxy] as ccep
}

[Istio Policy\nMixer] as ipm
[Adapter service] as cas

node "Adapter Pod1" {
    [Envoy Proxy1] as cep1
    [Adapter1] as ca1
}

node "Adapter Pod2" {
    [Envoy Proxy2] as cep2
    [Adapter2] as ca2
}

node "Server pod" {
    [Server Envoy Proxy] as sep
    [Server] as s
}

cc -> ccep: HTTP server request
ccep -> ipm : [1] policy grpc\n(retry=2)

ipm -> cas : grpc (over IPTables proxy)\nreconnect on close

cep1 -> ca1 : grpc
cep2 -> ca2 : grpc

cas .up-> cep1
cas .down.> cep2

ccep -down-> sep : [2] HTTP request
sep -> s

@enduml
